export enum ProjectCategory {
  ExperimentalStudies = 'Experimental studies',
  ObservationalStudies = 'Observational studies',
  QualitativeResearch = 'Qualitative research',
  QuantitativeResearch = 'Quantitative research',
  BasicTheoreticalResearch = 'Basic (theoretical) research',
  AppliedPracticalResearch = 'Applied (practical) research',
  LongitudinalStudies = 'Longitudinal studies',
  CrossSectionalStudies = 'Cross-sectional studies',
  RetrospectiveStudies = 'Retrospective studies',
  ProspectiveStudies = 'Prospective studies',
  MetaAnalysis = 'Meta-analysis',
  CorrelationalResearch = 'Correlational research',
  RandomizedControlledTrials = 'Randomized controlled trials (RCTs)',
  CaseStudies = 'Case studies',
  ActingStudiesEthnography = 'Acting Studies (Ethnography)',
}
